name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    uses: the-culinari/workflows/.github/workflows/release-please.yml@main
    with:
      release-type: "node"
