name: Secret Scanning

on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  secret-scanning:
    permissions:
      contents: read
      security-events: write
    uses: the-culinari/workflows/.github/workflows/secret-scanning.yml@main
