name: Secret Scanning

on: [workflow_dispatch]

jobs:
  secret-scanning:
    permissions:
      contents: read
      security-events: write
    uses: The-Culinari/workflows/.github/workflows/secret-scanning.yml@main
